# Generated by Django 3.2.23 on 2023-12-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='dare_added',
            new_name='date_added',
        ),
    ]
